### ISSUE TITLE
java.lang.IllegalArgumentException: profile [xxx] not found

### ISSUE THREAD

**Issue by cecom** [cecom/pomutils#4]
If you have a profile which is new or missing on one side of the merge, you get an exception like:

Exception in thread "main" java.lang.IllegalArgumentException: profile [generate-erp-ws] not found
        at de.oppermann.pomutils.util.POM.getProfileProperties(POM.java:222)
        at de.oppermann.pomutils.util.POM.getProfileProperty(POM.java:209)
        at de.oppermann.pomutils.rules.PropertyRule.evaluate(PropertyRule.java:86)
        at de.oppermann.pomutils.rules.Ruleset.evaluate(Ruleset.java:82)
        at de.oppermann.pomutils.PomMergeDriver.merge(PomMergeDriver.java:62)
        at de.oppermann.pomutils.Main.executePomMergeDriver(Main.java:89)
        at de.oppermann.pomutils.Main.mainInternal(Main.java:77)
        at de.oppermann.pomutils.Main.main(Main.java:46)

**Comment by cecom** [comment]
Fixed with v1.3
